config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :users do
    resources :tasks
    patch 'pause/tasks/:task_id' => 'tasks#toggle_pause_flag', :as => :task_toggle_pause
    patch 'done/tasks/:task_id' => 'tasks#finish_task', :as => :finish_task
  end

  post 'logout' => 'oauths#destroy', :as => :logout

  get  'static_pages/about'
  resources :posts

  resource :user
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  get "tweet/:user_id" => "tweets#tweet", :as => :tweet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  enum repeat_interval: { one_time: 0, every_day: 1, every_week: 2 }
  enum tweet_dayofweek: { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }
  enum pause_flag: { active: 0, pause: 1 }
  enum pause_flag: { todo: 0, done: 1 }

  validates :title, presence: true
  validates :tweet_content, presence: true
  validates :status, presence: true
  validates :pause_flag, presence: true

  def toggle_pause_flag!
    if active?
      pause!
    else
      active!
    end
  end

  def update_tweet_datetime
    if (!one_time? && tweet_datetime < Time.current)
      # 指定日時・時刻を文字列で取得
      today = Time.current.to_date.to_s
      tweet_time_text = tweet_time.to_s.split[1]
      today_tweet_datetime = (today + ' ' + tweet_time_text).in_time_zone
      if every_day?
        self.tweet_datetime = (Date.tomorrow.to_s + ' ' + tweet_time_text).in_time_zone
      elsif task.every_week?
        # 次の指定曜日の日付を取得
        next_wday = Time.current.beginning_of_week(task.tweet_dayofweek.to_sym).since(1.week)
        self.tweet_datetime = (next_wday.to_date.to_s + ' ' + tweet_time_text).in_time_zone
      end
      self.save!
    end
  end

  def tweet
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.twitter[:api_key]
      config.consumer_secret     = Rails.application.credentials.twitter[:api_secret_key]
      config.access_token        = user.access_token
      config.access_token_secret = user.access_token_secret
    end
    begin
      client.update!(self.tweet_content)
    rescue => e
      logger.error e.backtrace.join("\n")
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    set_tweet_datetime(@task)
    if @task.save
      redirect_to user_path(@task.user)
    else
      # render user_path(@task.user)
      # render template: 'users/show'
      redirect_to user_path(@task.user)
    end
  end

  def update
    @task = current_user.tasks.find(params[:id])
    tweet_year = params[:task][:tweet_date_year] || '1999'
    tweet_month = params[:task][:tweet_date_month] || '01'
    tweet_day = params[:task][:tweet_date_day] || '01'
    tweet_hour = params[:task][:tweet_time_hour] || '01'
    tweet_minute = params[:task][:tweet_time_minute] || '01'
    time = Time.zone.parse("#{tweet_year}-#{tweet_month}-#{tweet_day} #{tweet_hour}:#{tweet_minute}:00")

    @task.tweet_date = time
    puts 'tweet_date'
    puts @task.tweet_date
    @task.tweet_time = time
    puts 'tweet_time'
    puts @task.tweet_time
    @task.title = params[:task][:title]
    @task.repeat_interval = params[:task][:repeat_interval]
    @task.tweet_dayofweek = params[:task][:tweet_dayofweek]
    @task.tweet_content = params[:task][:tweet_content]
    set_tweet_datetime(@task)
    if @task.save
      render json: { tweet_datetime: @task.tweet_datetime.strftime('%Y-%m-%d %H:%M') }, status: :ok
    else
      render json: { task: @task, errors: { messages: @task.errors.full_messages } }, status: :bad_request
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:task_id])
    task_title = @task.title
    if @task.destroy
      render json: { task_title: task_title  }
    else
      render json: { task: @task, errors: { messages: @task.errors.full_messages  } }, status: :bad_request
    end
  end

  def toggle_pause_flag
    @task = current_user.tasks.find(params[:task_id])
    if @task.toggle_pause_flag!
      render json: { task: @task }, status: :ok
      # render partial: 'tasks/crud_menus', locals: { task: @task }
    else
      render json: { task: @task, errors: { messages: @task.errors.full_messages  } }, status: :bad_request
    end
  end

  def finish_task
    @task = current_user.tasks.find(params[:task_id])
    if @task.done!
      render json: { task: @task }, status: :ok
    else
      render json: { task: @task, errors: { messages: @task.errors.full_messages  } }, status: :bad_request
    end
  end

  def task_params
    params.require(:task).permit(:title, :repeat_interval, :tweet_date, :tweet_time, :tweet_dayofweek, :tweet_content, :pause_flag, :user_id)
  end

  def task_update_params
    params.require(:task).permit(:title, :tweet_content, :repeat_interval, :tweet_date, :tweet_time, :tweet_month, )
  end

  # 直近のツイート日時を作成
  def set_tweet_datetime(task)
    wday = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
    # 指定時刻を文字列で取得
    tweet_time = task.tweet_time.to_s.split[1]
    today = Time.current.to_date.to_s
    today_tweet_datetime = (today + ' ' + tweet_time).in_time_zone
    if task.one_time?
      tweet_datetime = task.tweet_date.to_s + ' ' + tweet_time
      task.tweet_datetime = tweet_datetime.in_time_zone
      task.tweet_dayofweek = nil
    elsif task.every_day?
      if today_tweet_datetime > Time.current
        task.tweet_datetime = today_tweet_datetime
      else
        task.tweet_datetime = (Date.tomorrow.to_s + ' ' + tweet_time).in_time_zone
      end
      task.tweet_date = nil
      task.tweet_dayofweek = nil
    elsif task.every_week?
      # タスク新規作成日が指定曜日かつ現在時刻が指定時刻より未来の場合
      if (task.tweet_dayofweek == wday[Time.current.wday]) && (today_tweet_datetime > Time.current)
        task.tweet_datetime = today_tweet_datetime
      else
        # 次の指定曜日の日付を取得
        next_wday = Time.current.beginning_of_week(task.tweet_dayofweek.to_sym).since(1.week)
        task.tweet_datetime = (next_wday.to_date.to_s + ' ' + tweet_time).in_time_zone
      end
      task.tweet_date = nil
    end
  end

end

app/views/tasks/_crud_menus.html.slim
ul.list-inline.justify-content-center id="js-taskCrudList-#{task.id}" style="float: right;"
  - if task.done?
    li.list-inline-item
     | 完了済
  - else
    li.list-inline-item id="js-taskFinish-#{task.id}"
      = link_to '#', class: 'js-taskFinish', data: { confirm: 'タスクを完了しますか？', url: "#{user_finish_task_path(current_user.id, task.id)}", taskid: "#{task.id}" } do
        button.btn.btn-outline-secondary 完了する
    - if task.pause?
      li class="list-inline-item js-taskPause-#{task.id}"
        = link_to '#', class: 'js-taskPause', data: { confirm: 'タスクを再開しますか？', url: "#{user_task_toggle_pause_path(task.user.id, task.id)}", taskid: "#{task.id}" } do
          i.fas.fa-play-circle.font-awesome
    - else
      li class="list-inline-item js-taskPause-#{task.id}"
        = link_to '#', class: 'js-taskPause', data: { confirm: 'タスクを中断しますか？', url: "#{user_task_toggle_pause_path(task.user.id, task.id)}", taskid: "#{task.id}" } do
          i.fas.fa-pause.font-awesome
    li.list-inline-item id="js-taskEdit-#{task.id}"
      i.js-taskEdit.fas.fa-pencil-alt.font-awesome data-task-id='#{task.id}'
  li.list-inline-item
    = link_to '#', class: 'js-taskDelete', data: { confirm: '削除しますか？', url: "#{user_task_path(task.user.id, task.id)}", taskid: "#{task.id}" } do
      i.fa.fa-trash.font-awesome

app/views/tasks/_form.html.slim
= form_with model: [user, task], local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group#js-repeatInterval
    = f.label :repeat_interval
    .period-radio
      = f.radio_button :repeat_interval, :one_time, class: 'mr-1'
      = f.label :repeat_interval, 'one time', { value: :one_time }
      = f.radio_button :repeat_interval, :every_day, class: 'ml-4 mr-1'
      = f.label :repeat_interval, 'every day', { value: :every_day }
      = f.radio_button :repeat_interval, :every_week, class: 'ml-4 mr-1'
      = f.label :repeat_interval, 'every week', { value: :every_week }

  .form-group#js-tweetDate
    = f.label :tweet_date
    = f.date_select :tweet_date, {start_year: Time.current.year, default: Time.current}

  .form_group#weekInterval
    = f.label :tweet_dayofweek
    div
      = f.radio_button :tweet_dayofweek, :sunday, class: 'mr-1', checked: 'checked'
      = f.label :tweet_dayofweek, 'Sun', { value: :sunday }
      = f.radio_button :tweet_dayofweek, :monday, class: 'ml-4 mr-1'
      = f.label :tweet_dayofweek, 'Mon', { value: :monday }
      = f.radio_button :tweet_dayofweek, :tuesday, class: 'ml-4 mr-1'
      = f.label :tweet_dayofweek, 'Tue', { value: :tuesday }
      = f.radio_button :tweet_dayofweek, :wednesday, class: 'ml-4 mr-1'
      = f.label :tweet_dayofweek, 'Wed', { value: :wednesday }
      = f.radio_button :tweet_dayofweek, :thursday, class: 'ml-4 mr-1'
      = f.label :tweet_dayofweek, 'Thu', { value: :thursday }
      = f.radio_button :tweet_dayofweek, :friday, class: 'ml-4 mr-1'
      = f.label :tweet_dayofweek, 'Fri', { value: :friday }
      = f.radio_button :tweet_dayofweek, :saturday, class: 'ml-4 mr-1'
      = f.label :tweet_dayofweek, 'Sat', { value: :saturday }

  .form-group
    = f.label :tweet_time
    = f.time_select :tweet_time
  .form-group
    = f.label :tweet_content
    = f.text_area :tweet_content, cols: '50', rows: '3', class: 'form-control'

  .mb-2
    button#js-cancelNewTaskBtn.btn.btn-outline-primary.mr-1 cancel
    = f.button :submit, style: 'display:block', class: 'btn btn-primary', style: display='inline-block'

app/views/tasks/_task.html.slim
div id='js-task-#{task.id}' class='row'
  .col-lg-8.offset-lg-2
    table id='js-task-#{task.id}' class='table'
      tr
        div id='js-taskFailedFlash-#{task.id}'
        td
          div id='js-taskTitle-#{task.id}'
             = task.title
          div id='js-taskRepeatInterval-#{task.id}' style='display:inline-block'
            = task.repeat_interval
          - if task.repeat_interval == 'every_week'
            p id='js-taskTweetDayOfWeek-#{task.id}' class='ml-2' style='display:inline-block'
              = task.tweet_dayofweek

          p id='js-taskTweetDateTime-#{task.id}'
            = task.tweet_datetime.strftime('%Y-%m-%d %H:%M')
          div id='js-taskBody-#{task.id}'
            = simple_format(task.tweet_content)

          = form_with id:"js-taskEditForm-#{task.id}", class: 'taskEditForm', local: 'true' do |f|
            .form-group
              = f.label :title
              = f.text_field id="js-taskEditTitle-#{task.id}", class: 'form-control', style:'display=block'
            .form-group
              = f.label :repeat_interval
              .period-radio
                input type='radio' id="js-one_time-#{task.id}" class='js-oneTimeRadioBtn mr-1' name="editRepeatInterval-#{task.id}" value='one_time' data-task-id="#{task.id}"
                label for="js-one_time-#{task.id}" one_time
                input type='radio' id="js-every_day-#{task.id}" class='js-everyDayRadioBtn ml-4 mr-1' name="editRepeatInterval-#{task.id}" value='every_day' data-task-id="#{task.id}"
                label for="js-every_day-#{task.id}" every_day
                input type='radio' id="js-every_week-#{task.id}" class='js-everyWeekRadioBtn ml-4 mr-1' name="editRepeatInterval-#{task.id}" value='every_week' data-task-id="#{task.id}"
                label for="js-every_week-#{task.id}" every_week

            div id="js-taskEditTweetDate-#{task.id}" class= 'group-form'
              = f.label id="js-tweet_date-#{task.id}", 'tweet_date', class: 'mr-2'
              = f.date_select id="js-tweet_date-#{task.id}", {start_year: Time.current.year, default: task.tweet_date}

            div id="js-taskEditTweetDayOfWeek-#{task.id}" class= 'group-form'
              = f.label :tweet_dayofweek
              div
                input type='radio' id="js-sun-#{task.id}" class='mr-1' name="editTweetDayOfWeek-#{task.id}" value='sunday'
                label for="js-sun-#{task.id}" Sun
                input type='radio' id="js-mon-#{task.id}" class='ml-4 mr-1' name="editTweetDayOfWeek-#{task.id}" value='monday'
                label for="js-mon-#{task.id}" Mon
                input type='radio' id="js-tue-#{task.id}" class='ml-4 mr-1' name="editTweetDayOfWeek-#{task.id}" value='tuesday'
                label for="js-tue-#{task.id}" Tue
                input type='radio' id="js-wed-#{task.id}" class='ml-4 mr-1' name="editTweetDayOfWeek-#{task.id}" value='wednesday'
                label for="js-wed-#{task.id}" Wed
                input type='radio' id="js-thu-#{task.id}" class='ml-4 mr-1' name="editTweetDayOfWeek-#{task.id}" value='thursday'
                label for="js-thu-#{task.id}" Thu
                input type='radio' id="js-fri-#{task.id}" class='ml-4 mr-1' name="editTweetDayOfWeek-#{task.id}" value='friday'
                label for="js-fri-#{task.id}" Fri
                input type='radio' id="js-sat-#{task.id}" class='ml-4 mr-1' name="editTweetDayOfWeek-#{task.id}" value='saturday'
                label for="js-sat-#{task.id}" Sat

            .form-group
              = f.label :tweet_time, for:"js-taskEditTweetTime-#{task.id}"
              = f.time_select id="js-taskEditTweetTime-#{task.id}", { default: task.tweet_time }, class: 'mb-1'
            .form-group
              = f.label :tweet_content
              = f.text_area id="js-taskEditBody-#{task.id}", class:'form-control mb-1', style:'display:block', cols: '50', rows: '3'
            a.js-taskEditCancel.btn.btn-light data-task-id='#{task.id}' cancel
            a.js-taskUpdate.btn.btn-success[data-url='#{user_task_path(task.user.id, task.id)}'
                                               data-user-id='#{task.user.id}'
                                               data-task-id='#{task.id}'
                                              ]
                                              |update
        td.action
          div id="js-taskCrudMenus-#{task.id}"
            = render 'tasks/crud_menus', { user: task.user, task: task }

app/views/tasks/toggle_pause_flag.js.slim
$(“#js-taskCrudMenus-#{@task.id}”).html(“#{j(render ‘tasks/crud_menus')}")