config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :users do
    resources :tasks
    patch 'pause/tasks/:task_id' => 'tasks#toggle_pause_flag', :as => :task_toggle_pause
    patch 'done/tasks/:task_id' => 'tasks#finish_task', :as => :finish_task
  end

  post 'logout' => 'oauths#destroy', :as => :logout

  get  'static_pages/about'
  resources :posts

  resource :user
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  get "tweet/:user_id" => "tweets#tweet", :as => :tweet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :authentications, dependent: :destroy
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :authentications

  validates :name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
    @task = Task.new
  end

end

app/views/users/show.html.slim
  p
    strong USER ID   :
    = current_user.id
  p
    strong USER NAME :
    = current_user.name
  <br>
  = link_to 'Tweet', tweet_path(current_user.id)
  = link_to 'Back', users_path

  .row
    .offset-md-2.col-md-8


      button#js-newTaskBtn.btn.btn-primary.mb-3 new task
      <!-- タスク作成フォーム -->
      #newTaskForm(style='display:none')
        = render 'tasks/form', { user: @user, task: @task }



  <!-- タスク一覧 -->
  #js-taskList
    = render @tasks


    = javascript_include_tag 'tasks/create_task.js'
    = javascript_include_tag 'tasks/edit_task.js'
    = javascript_include_tag 'tasks/update_task.js'
    = javascript_include_tag 'tasks/delete_task.js'
    = javascript_include_tag 'tasks/toggle_pause_flag.js'
    = javascript_include_tag 'tasks/finish_task.js'